default:
  - 'prepare'
  - 'build'

server:
  - 'shell:server'

prepare:
  - 'mkdir:site'
  - 'clean:site'
  - 'mkdir:siteDirs'

build:
  - 'newer:copy:indexHtml'
  - 'buildJsAll'
  - 'buildCss'
  - 'copyImages'
  - 'shouldWatch'

buildJsAll:
  - 'buildJsMain'
  - 'buildJsDeps'

buildJsMain:
  - 'newer:jshint:main'
  - 'browserify2:main'
  - 'shouldUglifyJsMain'

buildJsDeps:
  - 'uglify:jsDeps'

buildCss:
  - 'sass:main'
  - 'cssmin:main'

copyImages:
  - 'copy:img'

reloadImages:
  - 'clean:siteImages'
  - 'copyImages'